name: Use Custom Java Setup Action

on:
  pull_request:
    types:
      - merged
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Use Setup Java Action
        uses: your-username/your-repo-name@v1 # Replace with your repo and tag
        with:
          distribution: 'temurin'
          java-version: '17'
